org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official

GROUP=me.kozakov.orrery
VERSION_NAME=0.5.1-SNAPSHOT

POM_URL=https://github.com/koza4e4ok/Orrery
POM_SCM_URL=https://github.com/koza4e4ok/Orrery
POM_SCM_CONNECTION=scm:git:git://github.com/koza4e4ok/Orrery.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/koza4e4ok/Orrery.git
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=koza4e4ok
POM_DEVELOPER_NAME=Andrii Kozakov
POM_INCEPTION_YEAR=2026
